// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SimpleCalc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SimpleCalc.SharedLib.Generated {
  public static partial class CalculatorService
  {
    static readonly string __ServiceName = "CalculatorService";

    static readonly grpc::Marshaller<global::SimpleCalc.SharedLib.Generated.CalculatorRequest> __Marshaller_CalculatorRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SimpleCalc.SharedLib.Generated.CalculatorRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SimpleCalc.SharedLib.Generated.CalculatorReply> __Marshaller_CalculatorReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SimpleCalc.SharedLib.Generated.CalculatorReply.Parser.ParseFrom);

    static readonly grpc::Method<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply> __Method_Add = new grpc::Method<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Add",
        __Marshaller_CalculatorRequest,
        __Marshaller_CalculatorReply);

    static readonly grpc::Method<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply> __Method_Subtract = new grpc::Method<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Subtract",
        __Marshaller_CalculatorRequest,
        __Marshaller_CalculatorReply);

    static readonly grpc::Method<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply> __Method_Multiply = new grpc::Method<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Multiply",
        __Marshaller_CalculatorRequest,
        __Marshaller_CalculatorReply);

    static readonly grpc::Method<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply> __Method_Divide = new grpc::Method<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Divide",
        __Marshaller_CalculatorRequest,
        __Marshaller_CalculatorReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SimpleCalc.SharedLib.Generated.SimpleCalcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CalculatorService</summary>
    [grpc::BindServiceMethod(typeof(CalculatorService), "BindService")]
    public abstract partial class CalculatorServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SimpleCalc.SharedLib.Generated.CalculatorReply> Add(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SimpleCalc.SharedLib.Generated.CalculatorReply> Subtract(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SimpleCalc.SharedLib.Generated.CalculatorReply> Multiply(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SimpleCalc.SharedLib.Generated.CalculatorReply> Divide(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CalculatorService</summary>
    public partial class CalculatorServiceClient : grpc::ClientBase<CalculatorServiceClient>
    {
      /// <summary>Creates a new client for CalculatorService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CalculatorServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CalculatorService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CalculatorServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CalculatorServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CalculatorServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SimpleCalc.SharedLib.Generated.CalculatorReply Add(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Add(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SimpleCalc.SharedLib.Generated.CalculatorReply Add(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Add, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SimpleCalc.SharedLib.Generated.CalculatorReply> AddAsync(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SimpleCalc.SharedLib.Generated.CalculatorReply> AddAsync(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Add, null, options, request);
      }
      public virtual global::SimpleCalc.SharedLib.Generated.CalculatorReply Subtract(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Subtract(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SimpleCalc.SharedLib.Generated.CalculatorReply Subtract(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Subtract, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SimpleCalc.SharedLib.Generated.CalculatorReply> SubtractAsync(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubtractAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SimpleCalc.SharedLib.Generated.CalculatorReply> SubtractAsync(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Subtract, null, options, request);
      }
      public virtual global::SimpleCalc.SharedLib.Generated.CalculatorReply Multiply(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Multiply(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SimpleCalc.SharedLib.Generated.CalculatorReply Multiply(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Multiply, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SimpleCalc.SharedLib.Generated.CalculatorReply> MultiplyAsync(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MultiplyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SimpleCalc.SharedLib.Generated.CalculatorReply> MultiplyAsync(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Multiply, null, options, request);
      }
      public virtual global::SimpleCalc.SharedLib.Generated.CalculatorReply Divide(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Divide(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SimpleCalc.SharedLib.Generated.CalculatorReply Divide(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Divide, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SimpleCalc.SharedLib.Generated.CalculatorReply> DivideAsync(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DivideAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SimpleCalc.SharedLib.Generated.CalculatorReply> DivideAsync(global::SimpleCalc.SharedLib.Generated.CalculatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Divide, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CalculatorServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CalculatorServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CalculatorServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Add, serviceImpl.Add)
          .AddMethod(__Method_Subtract, serviceImpl.Subtract)
          .AddMethod(__Method_Multiply, serviceImpl.Multiply)
          .AddMethod(__Method_Divide, serviceImpl.Divide).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CalculatorServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Add, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply>(serviceImpl.Add));
      serviceBinder.AddMethod(__Method_Subtract, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply>(serviceImpl.Subtract));
      serviceBinder.AddMethod(__Method_Multiply, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply>(serviceImpl.Multiply));
      serviceBinder.AddMethod(__Method_Divide, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SimpleCalc.SharedLib.Generated.CalculatorRequest, global::SimpleCalc.SharedLib.Generated.CalculatorReply>(serviceImpl.Divide));
    }

  }
}
#endregion
